{{- if .Values.devicePlugin.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: volcano-vgpu-device-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nvidia-device-plugin.labels" . | nindent 4 }}
    app.kubernetes.io/component: volcano-vgpu-device-plugin
data:
  device-config.yaml: |-
    nvidia:
      resourceCountName: volcano.sh/vgpu-number
      resourceMemoryName: volcano.sh/vgpu-memory
      resourceMemoryPercentageName: volcano.sh/vgpu-memory-percentage
      resourceCoreName: volcano.sh/vgpu-cores
      overwriteEnv: false
      defaultMemory: 0
      defaultCores: 0
      defaultGPUNum: 1
      deviceSplitCount: 10
      deviceMemoryScaling: 1
      deviceCoreScaling: 1
      gpuMemoryFactor: 1
      knownMigGeometries:
        - models: [ "A30" ]
          allowedGeometries:
            - group: group1
              geometries:
                - name: 1g.6gb
                  memory: 6144
                  count: 4
            - group: group2
              geometries:
                - name: 2g.12gb
                  memory: 12288
                  count: 2
            - group: group3
              geometries:
                - name: 4g.24gb
                  memory: 24576
                  count: 1
        - models: [ "A100-SXM4-40GB", "A100-40GB-PCIe", "A100-PCIE-40GB", "A100-SXM4-40GB" ]
          allowedGeometries:
            - group: "group1"
              geometries:
                - name: 1g.5gb
                  memory: 5120
                  count: 7
            - group: "group2"
              geometries:
                - name: 2g.10gb
                  memory: 10240
                  count: 3
                - name: 1g.5gb
                  memory: 5120
                  count: 1
            - group: "group3"
              geometries:
                - name: 3g.20gb
                  memory: 20480
                  count: 2
            - group: "group4"
              geometries:
                - name: 7g.40gb
                  memory: 40960
                  count: 1
        - models: [ "A100-SXM4-80GB", "A100-80GB-PCIe", "A100-PCIE-80GB"]
          allowedGeometries:
            - group: "group1"
              geometries:
                - name: 1g.10gb
                  memory: 10240
                  count: 7
            - group: "group2"
              geometries:
                - name: 2g.20gb
                  memory: 20480
                  count: 3
                - name: 1g.10gb
                  memory: 10240
                  count: 1
            - group: "group3"
              geometries:
                - name: 3g.40gb
                  memory: 40960
                  count: 2
            - group: "group4"
              geometries:
                - name: 7g.79gb
                  memory: 80896
                  count: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: volcano-vgpu-node-config
  labels:
    {{- include "nvidia-device-plugin.labels" . | nindent 4 }}
    app.kubernetes.io/component: volcano-vgpu-node-plugin
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
    {
      "nodeconfig": [
        {
          "name": "aio-node67",
          "operatingmode": "hami-core",
          "devicememoryscaling": 1.8,
          "devicesplitcount": 10,
          "migstrategy":"none",
          "filterdevices": {
            "uuid": [],
            "index": []
          }
        }
      ]
    }
{{- end }}
