#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

set -x

# Initialize kubeconfig environment
KUBECONFIG_PATH="${HOME}/.kube"
KUBECONFIG_FILE="${KUBECONFIG_PATH}/config"
KUBECONFIG_DEMO="./hack/dummy-kubeconfig.yaml"

echo "Kubeconfig path: ${KUBECONFIG_FILE}"

# Check if kubeconfig file exists
if [ ! -f "${KUBECONFIG_FILE}" ]; then
  echo "Generating fake kubeconfig"

  # Ensure kubeconfig directory exists, and create if necessary
  if [ ! -d "${KUBECONFIG_PATH}" ]; then
    mkdir -p "${KUBECONFIG_PATH}"
  fi

  # Copy demo kubeconfig to the desired location
  cp "${KUBECONFIG_DEMO}" "${KUBECONFIG_FILE}"
else
  echo "Using existing local kubeconfig"
fi
