{{- if .Values.gpuStack.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "device-manager.fullname" . }}
  labels:
    {{- include "llmos-gpu-stack.labels" . | nindent 4 }}
  {{- with .Values.gpuStack.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.gpuStack.serviceAccount.automount }}
{{- end }}
