name: release

concurrency:
  group: release
  cancel-in-progress: true

on:
  push:
    tags:
      - v*

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ${{ vars.REGISTRY || 'ghcr.io/llmos-ai' }}
  DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY || 'docker.io/llmosai' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.16.2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: make test && make lint
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          install-only: true
      - name: Release llmos-gpu-stack
        run: make release-gpu-stack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run build llmos-gpu-stack charts
        run: make package-charts
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1
      - name: Run chart-testing (lint)
        run: |
          helm repo add nvidia https://helm.ngc.nvidia.com/nvidia
          helm repo add volcano https://volcano-sh.github.io/helm-charts
          ct lint --target-branch ${{ github.event.repository.default_branch }} --charts dist/charts/llmos-gpu-stack
      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0
      - name: Run chart-testing (install)
        run: |
          ct install --target-branch ${{ github.event.repository.default_branch }} --charts dist/charts/llmos-gpu-stack  --helm-dependency-extra-args "--skip-refresh"

  release-charts:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Run build llmos-gpu-stack charts
        run: make package-charts
      - name: Run chart-releaser
        uses: guangbochen/chart-releaser-action@main
        with:
          charts_dir: dist/charts
          skip_packaging: true
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CR_PACKAGE_PATH: dist/charts
          CLEAN_UP_CHARTS: "true"
